### ISSUE TITLE
Fait attention à l'instruction `open` 

### ISSUE THREAD

**Issue by bchhun** [MarieNoelleGrant/adventOfCode#1]
https://github.com/MarieNoelleGrant/adventOfCode/blob/4b858b58d4ddd4e4513601bc721f7cf45e4f7da5/day01/fuelCounter.py#L3

lorsque tu ouvres un fichier de cette manière, il ne se ferme pas implicitement. 

Imagine si tu ouvrais un gros fichier qui prenait tout ton espace mémoire...

Tu dois donc faire un `inputFile.close()` explicite à la fin du traitement de ton fichier.

Une autre solution est d'utiliser `with`: 

```
with open("input_day1.txt", "r") as masses:
  faitTaPatente(masses)
```

lorsque l'interpréteur python va se rendre à la fin de ton `with`, il va automatiquement fermé ton fichier :)

**Comment by MarieNoelleGrant** [comment]
C'est good! Je vais y penser pour les prochaines fois! Et j'aime bien la technique du with, ça permet de bien voir la portée de l'utilisation du fichier aussi.
